config/routes.rb
Rails.application.routes.draw do
  resources :sousgroupes

  resources :principalgroupes

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/principalgroupe.rb
class Principalgroupe < ActiveRecord::Base
  has_many :sousgroupes
end

app/models/sousgroupe.rb
class Sousgroupe < ActiveRecord::Base
  belongs_to :principalgroupe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/principalgroupes_controller.rb
class PrincipalgroupesController < ApplicationController
  before_action :set_principalgroupe, only: [:show, :edit, :update, :destroy]

  # GET /principalgroupes
  # GET /principalgroupes.json
  def index
    @principalgroupes = Principalgroupe.all
  end

  # GET /principalgroupes/1
  # GET /principalgroupes/1.json
  def show
  end

  # GET /principalgroupes/new
  def new
    @principalgroupe = Principalgroupe.new
  end

  # GET /principalgroupes/1/edit
  def edit
  end

  # POST /principalgroupes
  # POST /principalgroupes.json
  def create
    @principalgroupe = Principalgroupe.new(principalgroupe_params)

    respond_to do |format|
      if @principalgroupe.save
        format.html { redirect_to @principalgroupe, notice: 'Principalgroupe was successfully created.' }
        format.json { render :show, status: :created, location: @principalgroupe }
      else
        format.html { render :new }
        format.json { render json: @principalgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /principalgroupes/1
  # PATCH/PUT /principalgroupes/1.json
  def update
    respond_to do |format|
      if @principalgroupe.update(principalgroupe_params)
        format.html { redirect_to @principalgroupe, notice: 'Principalgroupe was successfully updated.' }
        format.json { render :show, status: :ok, location: @principalgroupe }
      else
        format.html { render :edit }
        format.json { render json: @principalgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /principalgroupes/1
  # DELETE /principalgroupes/1.json
  def destroy
    @principalgroupe.destroy
    respond_to do |format|
      format.html { redirect_to principalgroupes_url, notice: 'Principalgroupe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_principalgroupe
      @principalgroupe = Principalgroupe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def principalgroupe_params
      params.require(:principalgroupe).permit(:nom)
    end
end

app/controllers/sousgroupes_controller.rb
class SousgroupesController < ApplicationController
  before_action :set_sousgroupe, only: [:show, :edit, :update, :destroy]

  # GET /sousgroupes
  # GET /sousgroupes.json
  def index
    @sousgroupes = Sousgroupe.all
  end

  # GET /sousgroupes/1
  # GET /sousgroupes/1.json
  def show
  end

  # GET /sousgroupes/new
  def new
    @sousgroupe = Sousgroupe.new
  end

  # GET /sousgroupes/1/edit
  def edit
  end

  # POST /sousgroupes
  # POST /sousgroupes.json
  def create
    @sousgroupe = Sousgroupe.new(sousgroupe_params)

    respond_to do |format|
      if @sousgroupe.save
        format.html { redirect_to @sousgroupe, notice: 'Sousgroupe was successfully created.' }
        format.json { render :show, status: :created, location: @sousgroupe }
      else
        format.html { render :new }
        format.json { render json: @sousgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sousgroupes/1
  # PATCH/PUT /sousgroupes/1.json
  def update
    respond_to do |format|
      if @sousgroupe.update(sousgroupe_params)
        format.html { redirect_to @sousgroupe, notice: 'Sousgroupe was successfully updated.' }
        format.json { render :show, status: :ok, location: @sousgroupe }
      else
        format.html { render :edit }
        format.json { render json: @sousgroupe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sousgroupes/1
  # DELETE /sousgroupes/1.json
  def destroy
    @sousgroupe.destroy
    respond_to do |format|
      format.html { redirect_to sousgroupes_url, notice: 'Sousgroupe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sousgroupe
      @sousgroupe = Sousgroupe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sousgroupe_params
      params.require(:sousgroupe).permit(:name, :principalgroupe_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/principalgroupes_helper.rb
module PrincipalgroupesHelper
end

app/helpers/sousgroupes_helper.rb
module SousgroupesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Llienssuperssimple</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/principalgroupes/_form.html.erb
<%= form_for @principalgroupe, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :nom, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  principalgroupes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/principalgroupes/edit.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Principalgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principalgroupes/index.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Principalgroupe %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:nom) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @principalgroupes.each do |principalgroupe| %>
      <tr>
        <td><%= principalgroupe.id %></td>
        <td><%= principalgroupe.nom %></td>
        <td><%=l principalgroupe.created_at, format: :long %></td>
        <td>
          <%= link_to principalgroupe_path(principalgroupe), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to principalgroupe_path(principalgroupe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_principalgroupe_path,
            :class => 'btn btn-primary' %>

app/views/principalgroupes/new.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Principalgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/principalgroupes/show.html.erb
<%- model_class = Principalgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Principalgroupe %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:nom) %></dt>
      <dd><pre class="prettyprint"><%= @principalgroupe.nom %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              principalgroupes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_principalgroupe_path(@principalgroupe), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              principalgroupe_path(@principalgroupe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/sousgroupes/_form.html.erb
<%= form_for @sousgroupe, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sousgroupes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/sousgroupes/edit.html.erb
<%- model_class = Sousgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Sousgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sousgroupes/index.html.erb
<%- model_class = Sousgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Sousgroupe %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sousgroupes.each do |sousgroupe| %>
      <tr>
        <td><%= sousgroupe.id %></td>
        <td><%= sousgroupe.name %></td>
        <td><%=l sousgroupe.created_at, format: :long %></td>
        <td>
          <%= link_to sousgroupe_path(sousgroupe), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to sousgroupe_path(sousgroupe), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sousgroupe_path,
            :class => 'btn btn-primary' %>

app/views/sousgroupes/new.html.erb
<%- model_class = Sousgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Sousgroupe %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sousgroupes/show.html.erb
<%- model_class = Sousgroupe -%>
<div class="page-header">
  <h1><%=t '.title', :default => Sousgroupe %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @sousgroupe.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sousgroupes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sousgroupe_path(@sousgroupe), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sousgroupe_path(@sousgroupe),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>